### ISSUE TITLE
publish the last version to pypi

### ISSUE THREAD

**Issue by ycardon-pro** [Orange-OpenSource/ods-mkdocs-theme#10]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/ods-mkdocs-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/ods-mkdocs-theme/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi, could you publish the latest version of the ods-mkdocs-theme to pipy (https://pypi.org/project/ods-mkdocs-theme/)

The current version does not have the `copyright Orange 2023-2024` in the footer.

**Comment by julien-deramond** [comment]
Hi there @ycardon-pro 
Good catch! I've released a new v0.1.1 (see https://github.com/Orange-OpenSource/ods-mkdocs-theme/releases/tag/0.1.1).
We have released this project only one time so far, so please keep us in touch if everything's fine :)
I'm closing this issue but let the comments open if it doesn't work or if there are any issues
